import json
from pathlib import Path


FINAL_PREFIX = "FD"
RECOMMENDATION_PREFIX = "REC"
READINESS_DECISION_IDS = {"FD1", "FD2", "FD3"}


def load_json(path):
    with Path(path).open("r", encoding="utf-8") as file:
        return json.load(file)


def evaluate_conditions(conditions, working_memory):
    """Evaluate all, any, and not condition groups against working memory."""
    all_conditions = conditions.get("all", [])
    any_conditions = conditions.get("any", [])
    not_conditions = conditions.get("not", [])

    all_ok = all(item in working_memory for item in all_conditions)
    any_ok = True if not any_conditions else any(item in working_memory for item in any_conditions)
    not_ok = all(item not in working_memory for item in not_conditions)

    return all_ok and any_ok and not_ok


def forward_chain(selected_facts, rules):
    working_memory = set(selected_facts)
    triggered_rules = []
    explanation_steps = []

    changed = True
    while changed:
        changed = False
        for rule in rules:
            conclusion = rule["conclusion"]
            if conclusion in working_memory:
                continue
            if evaluate_conditions(rule.get("conditions", {}), working_memory):
                working_memory.add(conclusion)
                triggered_rules.append(rule)
                explanation_steps.append(
                    {
                        "rule_id": rule["id"],
                        "rule_name": rule["name"],
                        "conditions": rule.get("conditions", {}),
                        "conclusion": conclusion,
                        "conclusion_text": rule["conclusion_text"],
                        "explanation": rule["explanation"],
                    }
                )
                changed = True

    recommendation_ids = sorted(item for item in working_memory if item.startswith(RECOMMENDATION_PREFIX))
    rule_final_decisions = get_final_decisions(working_memory, triggered_rules)
    readiness = build_readiness_summary(selected_facts, working_memory, rule_final_decisions)
    final_decisions = ensure_readiness_final_decision(rule_final_decisions, readiness)
    score_fallback_decisions = [
        decision for decision in final_decisions if decision.get("source") == "score_fallback"
    ]
    recommendations = [
        {
            "id": rule["conclusion"],
            "text": rule["conclusion_text"],
            "rule_id": rule["id"],
            "rule_name": rule["name"],
            "explanation": rule["explanation"],
        }
        for rule in triggered_rules
        if rule.get("type") == "recommendation"
    ]

    return {
        "selected_facts": sorted(selected_facts),
        "working_memory": sorted(working_memory),
        "inferred_decisions": sorted(item for item in working_memory if item.startswith("D")),
        "final_decisions": final_decisions,
        "rule_based_final_decisions": rule_final_decisions,
        "score_fallback_decisions": score_fallback_decisions,
        "recommendation_ids": recommendation_ids,
        "recommendations": recommendations,
        "readiness": readiness,
        "readiness_score": readiness["score"],
        "score_based_level": readiness["score_level"],
        "main_priority_area": readiness["main_priority_area"],
        "triggered_rules": triggered_rules,
        "explanation_chain": build_explanation(selected_facts, explanation_steps),
    }


def get_final_decisions(working_memory, triggered_rules):
    final_rules = [
        rule
        for rule in triggered_rules
        if rule.get("type") == "final" and rule["conclusion"] in working_memory
    ]
    return [
        {
            "id": rule["conclusion"],
            "text": rule["conclusion_text"],
            "rule_id": rule["id"],
            "rule_name": rule["name"],
            "explanation": rule["explanation"],
            "source": "rule_based",
        }
        for rule in final_rules
    ]


def ensure_readiness_final_decision(final_decisions, readiness):
    has_readiness_decision = any(
        decision["id"] in READINESS_DECISION_IDS for decision in final_decisions
    )
    if has_readiness_decision:
        return final_decisions

    fallback_id = score_to_decision_id(readiness["score"])
    fallback_text = {
        "FD1": "High Internship Readiness",
        "FD2": "Medium Internship Readiness",
        "FD3": "Low Internship Readiness",
    }[fallback_id]
    fallback = {
        "id": fallback_id,
        "text": fallback_text,
        "rule_id": "SCORE-FALLBACK",
        "rule_name": "Score-based fallback final readiness",
        "explanation": (
            "This final readiness level was generated by the score-based fallback "
            "because no rule-based readiness decision was triggered."
        ),
        "source": "score_fallback",
    }
    return [fallback] + final_decisions


def score_to_decision_id(score):
    if score <= 39:
        return "FD3"
    if score <= 69:
        return "FD2"
    return "FD1"


def build_explanation(selected_facts, explanation_steps):
    return {
        "start": "User-selected facts were added to working memory.",
        "selected_facts": sorted(selected_facts),
        "steps": explanation_steps,
        "end": "Forward chaining stopped because no additional rule conclusions could be added.",
    }


def build_readiness_summary(selected_facts, working_memory, final_decisions):
    component_scores = calculate_readiness_score(selected_facts)
    total_score = sum(item["score"] for item in component_scores.values())
    score_level = score_to_level(total_score)
    final_ids = {decision["id"] for decision in final_decisions}

    combined_level = score_level

    priority_area, priority_detail = find_priority_area(component_scores)
    main_advice = choose_main_advice(priority_area, working_memory, final_ids)

    return {
        "score": total_score,
        "score_level": score_level,
        "level": combined_level,
        "component_scores": component_scores,
        "main_priority_area": priority_area,
        "priority_detail": priority_detail,
        "main_advice": main_advice,
    }


def calculate_readiness_score(selected_facts):
    facts = set(selected_facts)

    resume_score = 0
    if "F1" in facts and "F2" in facts:
        resume_score = 8
    elif "F1" in facts:
        resume_score = 5

    profile_score = 4 if "F12" in facts else 0
    cover_letter_score = 3 if "F22" in facts else 0
    documents_score = 3 if "F23" in facts else 0
    tailoring_bonus = 2 if "F2" in facts and "F22" in facts else 0
    application_materials = min(
        25, resume_score + profile_score + cover_letter_score + documents_score + tailoring_bonus
    )

    project_score = 0
    if "F16" in facts:
        project_score = 0
    elif {"F3", "F4", "F25", "F26", "F28"}.issubset(facts):
        project_score = 15
    elif {"F3", "F25"}.issubset(facts):
        project_score = 9
    elif "F3" in facts:
        project_score = 6

    if "F24" in facts:
        project_score += 2
    if "F27" in facts:
        project_score += 2
    project_portfolio = min(15, project_score)

    if "F15" in facts:
        technical_skills = 5
    elif {"F5", "F6", "F29", "F30", "F31", "F32"}.issubset(facts):
        technical_skills = 25
    elif {"F5", "F6", "F29", "F30", "F32"}.issubset(facts):
        technical_skills = 20
    elif {"F5", "F29", "F32"}.issubset(facts):
        technical_skills = 17
    elif "F5" in facts:
        technical_skills = 12
    else:
        technical_skills = 0
    if "F31" in facts and technical_skills:
        technical_skills = min(25, technical_skills + 2)

    if {"F33", "F34", "F35", "F36", "F8"}.issubset(facts):
        interview_preparation = 15
    elif {"F7", "F33"}.issubset(facts):
        interview_preparation = 10
    elif "F7" in facts:
        interview_preparation = 6
    else:
        interview_preparation = 0

    if {"F9", "F14", "F37", "F38"}.issubset(facts):
        career_direction = 10
    elif "F9" in facts:
        career_direction = 5
    else:
        career_direction = 0

    experience_score = 2 if "F11" in facts else 0
    soft_skill_score = 0
    if "F41" in facts:
        soft_skill_score += 1
    if "F42" in facts:
        soft_skill_score += 1
    if "F10" in facts:
        application_score = 4
    elif "F21" in facts:
        application_score = 2
    else:
        application_score = 0
    if "F39" in facts:
        application_score += 1
    if "F40" in facts:
        application_score += 1
    experience_progress = min(10, experience_score + soft_skill_score + application_score)

    return {
        "Application Materials": {"score": application_materials, "max": 25},
        "Project and Portfolio": {"score": project_portfolio, "max": 15},
        "Technical Skills": {"score": technical_skills, "max": 25},
        "Interview Preparation": {"score": interview_preparation, "max": 15},
        "Career Direction": {"score": career_direction, "max": 10},
        "Application Progress and Work Readiness": {"score": experience_progress, "max": 10},
    }


def score_to_level(score):
    if score <= 39:
        return "Low Internship Readiness"
    if score <= 69:
        return "Medium Internship Readiness"
    return "High Internship Readiness"


def find_priority_area(component_scores):
    ratios = [
        item["score"] / item["max"]
        for item in component_scores.values()
        if item["max"]
    ]
    if ratios and min(ratios) >= 0.8:
        return "Application Follow-up", {"score": 0, "max": 0}

    ranked = sorted(
        component_scores.items(),
        key=lambda item: item[1]["score"] / item[1]["max"] if item[1]["max"] else 0,
    )
    area, detail = ranked[0]
    return area, detail


def choose_main_advice(priority_area, working_memory, final_ids):
    if priority_area == "Application Follow-up":
        return "You are ready to apply actively; keep tracking applications and preparing for interviews."
    if "FD8" in final_ids or "D8" in working_memory:
        return "Clarify your target internship role before applying widely."
    if "FD5" in final_ids or priority_area == "Technical Skills":
        return "Strengthen technical foundations and prepare an explainable project."
    if "FD9" in final_ids or priority_area == "Project and Portfolio":
        return "Improve your resume, project evidence, and portfolio materials."
    if "FD6" in final_ids or priority_area == "Application Materials":
        return "Improve your resume, project evidence, and portfolio materials."
    if "FD7" in final_ids or priority_area == "Interview Preparation":
        return "Practice interview questions and project explanations before interviews."
    if "FD10" in final_ids or priority_area == "Application Progress and Work Readiness":
        return "Start or increase applications and track progress."
    return "Keep applying while improving the lowest-scoring preparation area."


def readable_conditions(conditions):
    parts = []
    for key in ("all", "any", "not"):
        values = conditions.get(key, [])
        if values:
            parts.append(f"{key.upper()}: {', '.join(values)}")
    return " | ".join(parts) if parts else "No conditions"


def readiness_level_key(readiness_level):
    if readiness_level.startswith("High"):
        return "high"
    if readiness_level.startswith("Medium"):
        return "medium"
    return "low"


def recommend_career_paths(major_id, inference_result, career_paths, limit=3):
    """Recommend internship role tracks from major, inferred readiness, and selected facts.

    This helper is intentionally deterministic and data-driven. The role titles,
    platform links, and source notes live in data/career_paths.json, while this
    function only performs lightweight matching over the existing working memory.
    """
    majors = career_paths.get("majors", {})
    role_tracks = career_paths.get("role_tracks", {})
    selected_facts = set(inference_result.get("selected_facts", []))

    if major_id not in majors:
        major_id = "other_it_related" if "other_it_related" in majors else next(iter(majors))
    major = majors[major_id]

    readiness = inference_result.get("readiness", {})
    readiness_level = readiness.get(
        "level",
        inference_result.get(
            "score_based_level",
            score_to_level(inference_result.get("readiness_score", 0)),
        ),
    )
    level_key = readiness_level_key(readiness_level)

    scored_tracks = []
    track_ids = major.get("track_ids", [])
    for order, track_id in enumerate(track_ids):
        track = role_tracks.get(track_id)
        if not track:
            continue
        required_facts = track.get("matching_facts", [])
        matching_facts = [fact_id for fact_id in required_facts if fact_id in selected_facts]
        missing_facts = [fact_id for fact_id in required_facts if fact_id not in selected_facts]
        score = (len(matching_facts) * 3) - len(missing_facts) + (len(track_ids) - order)
        scored_tracks.append((score, -order, track_id, track, matching_facts, missing_facts))

    scored_tracks.sort(reverse=True)
    recommended_tracks = []
    source_ids = set()
    matching_fact_union = set()

    for _, _, track_id, track, matching_facts, missing_facts in scored_tracks[:limit]:
        source_ids.update(track.get("source_ids", []))
        matching_fact_union.update(matching_facts)
        recommended_tracks.append(
            {
                "track_id": track_id,
                "track_name": track.get("display_text", {}).get("en", track_id),
                "display_text": track.get("display_text", {}),
                "recommended_titles": track.get("readiness_titles", {}).get(level_key, []),
                "fit_note": track.get("fit_notes", {}).get(level_key, ""),
                "matching_facts": matching_facts,
                "missing_facts": missing_facts,
                "source_ids": track.get("source_ids", []),
            }
        )

    platforms = recommend_job_platforms(career_paths.get("platforms", []), level_key)
    for platform in platforms:
        if platform.get("source_id"):
            source_ids.add(platform["source_id"])

    source_notes = {
        source_id: note
        for source_id, note in career_paths.get("source_notes", {}).items()
        if source_id in source_ids
    }

    return {
        "major_id": major_id,
        "major": major,
        "readiness_level": readiness_level,
        "readiness_key": level_key,
        "recommended_tracks": recommended_tracks,
        "platforms": platforms,
        "matching_facts": sorted(matching_fact_union),
        "source_notes": source_notes,
    }


def recommend_job_platforms(platforms, readiness_key):
    selected = [
        platform
        for platform in platforms
        if readiness_key in platform.get("readiness_fit", [])
    ]
    return selected or platforms
